services:
  database:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    networks:
      - ${DB_NETWORK}

networks:
  centro_treinamento_network:
    driver: bridge

