springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  application:
    name: apiCentroTreinamento

  datasource:
    url: jdbc:postgresql://localhost:5432/centro_treinamento_db
    username: postgres
    password: 2004  
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


mail:
    host: smtp.mailtrap.io
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.mailtrap.io
      mail.smtp.debug: true
      mail.transport.protocol: smtp
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 30000
      mail.smtp.writetimeout: 5000
      mail.smtp.connection.timeout: 5000
      


jwt:
  secret: ${SECRET_KEY}  # Definir no ambiente

mercado:
  pago:
    access:
      token: ${MERCADO_PAGO_ACCESS_TOKEN}  # Definir no ambiente
